name = "Haven's Hearth"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad5f20678bf4d96341f9feec23fd32fcf0d6e91a8cc96a5e7a0f34c5c135e34d"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
