name = "Haven's Hearth"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "584082cb81beb339a9f5d5d19b5a80fbd62171105e6d917baa5f18ed57f339b6"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
