name = "Haven's Hearth"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "543f1ae9f01ff8449755930a439a7808ee0d013124a44240c371bbcf7c010ee9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
