name = "Haven's Hearth"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a6653d2f92e6d455fd1658eed6bb08d1d3eb6b6c677dc1142dbbcea7b4816a9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
