name = "Haven's Hearth"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db30e711fd76b0110880e03bd3fdb5f2014e25ef5761530182d04daa5327902c"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
